### PR TITLE
Support pre-IRIS installation

### LINKED ISSUE #31: Support installation pre-IRIS w/o package manager
We want to support 2016.1+ (maybe 2016.2+ for simplicity if JSON ends up mattering)
Should also cover generation of some artifact that can be installed on IRIS instances without using the package manager (maybe w/ Studio Project packaging? though that'll be challenging for the web resources)

### PR DESCRIPTION
**Pull request by isc-tleavitt**
Fixes #31 

This is still a WIP, but putting it up for comment in advance

### CODE REVIEW

**Comment by isc-tleavitt** [comment]
Current blockers:
* I'm having trouble getting a functional Ensemble instance installed to test on - having weird private webserver issues. Going to try again with a different kit Monday.
* SourceControl.Git.Change is a subextent of %Studio.SourceControl.Change which isn't allowed pre-IRIS because %Studio.SourceControl.Change is (or at least SHOULD be) in a read-only database. Rules on subextents changed in IRIS.

Draft artifact in case somebody sees this and wants to give it a try - just extract the .xml and `do $system.OBJ.Load(that file,"ck")`:
[GitSourceControl_CE.zip](https://github.com/intersystems/git-source-control/files/10144166/GitSourceControl_CE.zip)

**Comment by isc-tleavitt** [comment]
Another issue, namespace change on gitprojectsettings.csp doesn't work automatically and will need to change a bit to work pre-IRIS. (Probably a difference in the default template for /isc/studio/usertemplates.)

**Comment by isc-tleavitt** [comment]
[GitSourceControl_CE.zip](https://github.com/intersystems/git-source-control/files/10169951/GitSourceControl_CE.zip)

Updated artifact attached.

**Comment by isc-tleavitt** [comment]
@isc-pbarton I'll want to add docs on producing + loading the artifact as well before publishing... in short, it's just:
do ##class(SourceControl.Git.Utils).BuildCEInstallationPackage("GitSourceControl_CE.xml")

Then:
do $System.OBJ.Load("GitSourceControl_CE.xml","ck")

**Review by isc-pbarton — APPROVED** [review]
Tested this out on my Cache 2018.1.7 instance, looks to be working.

**Comment by isc-tleavitt** [comment]
Committing this as-is, will doc and automate later.

**Pull request merged**
