### PR TITLE
Terminate git pull on error

### LINKED ISSUE #545: Terminate Git Pull if Errors
We should add argumnets to SourceControl.Git.API.Pull() method that should terminate a pull process with an OS level error if there is an error with the git pull, default to zero.

### PR DESCRIPTION
**Pull request by isc-etamarch**
fixes #545

### CODE REVIEW

**Comment by isc-etamarch** [comment]
Should also fix #342 if the pull is done using the terminateOnError argument

**Review by isc-tleavitt — CHANGES_REQUESTED** [review]
Ultimately these are two distinct issues.

The terminate from #545 is a reference to $System.Process.Terminate, as used here (for example): https://github.com/intersystems/ipm/blob/master/src/%25ZPM/PackageManager.cls#L432 - this is for use from CI/CD scripts/pipelines/etc.

We *don't* want to use this in a CSP context, ever. Terminating the process with an OS-level error is too heavy-handed. From other contexts, there is a possible improvement to error reporting/logging, but it's possible that other changes over the summer have made the original requirement/issue moot. Try testing out with a bad SSH key on an SSH remote and see what pull does now.

**Comment by isc-etamarch** [comment]
Pravin tested and closed #342 because it no longer applies.

**Review by isc-tleavitt — CHANGES_REQUESTED** [review]
Last thing - can you explicitly test that terminateOnError has the desired effect if an error occurs in the pull event handler? e.g., something fails to compile

**Comment by isc-tleavitt** [comment]
> Last thing - can you explicitly test that terminateOnError has the desired effect if an error occurs in the pull event handler? e.g., something fails to compile

@isc-etamarch I can answer this through code inspection:
When SourceControl.Git.Utils:RunGitCommandWithInput runs the pull event handler, if an error occurs it puts the pull event handler output in errStream rather than outStream but doesn't return an error code.

We should have it return an error code in this case.

**Comment by isc-etamarch** [comment]
> > Last thing - can you explicitly test that terminateOnError has the desired effect if an error occurs in the pull event handler? e.g., something fails to compile
> 
> @isc-etamarch I can answer this through code inspection: When SourceControl.Git.Utils:RunGitCommandWithInput runs the pull event handler, if an error occurs it puts the pull event handler output in errStream rather than outStream but doesn't return an error code.
> 
> We should have it return an error code in this case. Note, this is a higher risk change and we'll need to ensure other callers do the right thing. Alternatively we could do something hacky with a % variable we intentionally leak.

SourceControl.Git.Utils:Pull checks the output of errStream for error / fatal. Should we also check for an ERROR, and would that grab the issue?

**Comment by isc-tleavitt** [comment]
> SourceControl.Git.Utils:Pull checks the output of errStream for error / fatal. Should we also check for an ERROR, and would that grab the issue?

Yes, that would do it.

**Comment by isc-tleavitt** [comment]
@isc-etamarch on this: just check for ERROR and call it a day.

**Pull request merged**
